{{- if .Values.operator.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cupcake.serviceAccountName" . }}
  namespace: {{ include "cupcake.namespace" . }}
  labels:
    {{- include "cupcake.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.agent.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cupcake.agent.serviceAccountName" . }}
  namespace: {{ include "cupcake.namespace" . }}
  labels:
    {{- include "cupcake.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
