apiVersion: cupcake.ricardomolendijk.com/v1
kind: DirectUpdate
metadata:
  name: upgrade-multi-step
spec:
  # Multi-step upgrade from 1.25.x to 1.28.x
  # CUPCAKE will automatically upgrade through: 1.25 → 1.26 → 1.27 → 1.28
  targetVersion: "1.28.0"
  components:
    - kubeadm
    - kubelet
    - kubectl
  strategy: rolling
  concurrency: 1
  preflightChecks: true
  # Each step will backup etcd before proceeding
  operationTimeout: "6h"  # Extended timeout for multiple steps
  nodeTimeout: "30m"
