apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scheduledupdates.cupcake.ricardomolendijk.com
spec:
  group: cupcake.ricardomolendijk.com
  names:
    kind: ScheduledUpdate
    listKind: ScheduledUpdateList
    plural: scheduledupdates
    singular: scheduledupdate
    shortNames:
      - su
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - targetVersion
                - scheduleAt
              properties:
                targetVersion:
                  type: string
                  description: "Kubernetes version e.g. 1.27.4"
                scheduleAt:
                  type: string
                  format: date-time
                  description: "When to start the upgrade"
                components:
                  type: array
                  items:
                    type: string
                  default:
                    - kubeadm
                    - kubelet
                    - kubectl
                strategy:
                  type: string
                  enum:
                    - rolling
                    - parallel
                    - canary
                  default: rolling
                concurrency:
                  type: integer
                  minimum: 1
                  default: 1
                canary:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    nodes:
                      type: array
                      items:
                        type: string
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                preflightChecks:
                  type: boolean
                  default: true
                airGapped:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    bundleConfigMap:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Scheduled
                    - Executing
                    - Completed
                    - Failed
                    - Cancelled
                scheduledFor:
                  type: string
                  format: date-time
                executedAt:
                  type: string
                  format: date-time
                directUpdateName:
                  type: string
                  description: "Name of created DirectUpdate CR"
                message:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Target
          type: string
          jsonPath: .spec.targetVersion
        - name: Scheduled
          type: string
          jsonPath: .spec.scheduleAt
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
